- LevelAutomation:
    EXP_07:
      characters: ''
      isAuto: false
      isFreeAuto: false
    EXP_08:
      characters: ''
      isAuto: false
      isFreeAuto: false
    EXP_09:
      characters: ''
      isAuto: false
      isFreeAuto: false
    EXP_10:
      characters: ''
      isAuto: false
      isFreeAuto: false
- Material_Mission:
    mission: EXP_07,EXP_08,EXP_09,EXP_10
