- LevelAutomation:
    ENCA_08:
      characters: "\u4F0A\u5357\u5A1C,\u5609\u897F\u5A6D,\u99AC\u683C\u52AA\u65AF"
      isAuto: true
      isFreeAuto: false
    EXP_08:
      characters: "\u85E5\u5291\u5E2B \"\u5FD7\u9858\u8005\",\u50AD\u5175 \"\u98A8\
        \u66B4\u795E\u65A7\",\u5012\u540A\u4EBA \"\u71ED\u706B\""
      isAuto: true
      isFreeAuto: false
    TRTC_08:
      characters: "\u50AD\u5175 \"\u708E\u4E4B\u9B54\u5973\",\u821E\u5B43 \"\u8774\
        \u8776\",\u5149\u8F1D\u885B\u571F\"\u9B54\u7981\""
      isAuto: true
      isFreeAuto: false
- Material_Mission:
    mission: EXP_08,ENCA_08,TRTC_08
